In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('data1.xlsx')

In [6]:
df[3:5]

,H,라인,투입시간,생산일자(완성),파트시리얼,SRING_Assy_DATA,SEAL_PRESS_LOAD,SEAL_PRESS_DISTANCE,NR_DATA#1,NR_DATA#2,...,IVM_Cover_체결_토크_1,IVM_Cover_체결_토크_2,IVM_Cover_체결_토크_3,IVM_Cover_체결_토크_4,IVM_Cover_체결_토크_5,IVM_Cover_체결_토크_6,Bottom_다윌핀_압입력_1,Bottom_다윌핀_압입력_2,캠스프라켓_체결_토크,완성_리크테스트값
3,신U 조립,U,2019-06-01 오전 8:41:29,2019-06-01 오전 9:46:20,19051623360149A,0.798,32.227,141.399,10.8,10.8,...,11.5,11.5,11.5,11.5,11.6,11.5,468.750,388.184,107.1,-13.169
4,신U 조립,U,2019-06-01 오전 8:41:50,2019-06-01 오전 9:47:31,19051623350148A,0.611,39.551,141.399,10.8,10.8,...,11.5,11.5,11.5,11.5,11.5,11.6,427.735,360.352,107.1,0.913

In [7]:
df.loc[3:5]

,H,라인,투입시간,생산일자(완성),파트시리얼,SRING_Assy_DATA,SEAL_PRESS_LOAD,SEAL_PRESS_DISTANCE,NR_DATA#1,NR_DATA#2,...,IVM_Cover_체결_토크_1,IVM_Cover_체결_토크_2,IVM_Cover_체결_토크_3,IVM_Cover_체결_토크_4,IVM_Cover_체결_토크_5,IVM_Cover_체결_토크_6,Bottom_다윌핀_압입력_1,Bottom_다윌핀_압입력_2,캠스프라켓_체결_토크,완성_리크테스트값
3,신U 조립,U,2019-06-01 오전 8:41:29,2019-06-01 오전 9:46:20,19051623360149A,0.798,32.227,141.399,10.8,10.8,...,11.5,11.5,11.5,11.5,11.6,11.5,468.750,388.184,107.1,-13.169
4,신U 조립,U,2019-06-01 오전 8:41:50,2019-06-01 오전 9:47:31,19051623350148A,0.611,39.551,141.399,10.8,10.8,...,11.5,11.5,11.5,11.5,11.5,11.6,427.735,360.352,107.1,0.913
5,신U 조립,U,2019-06-01 오전 8:42:20,2019-06-01 오전 9:48:15,19051623370150A,0.523,35.157,141.399,10.7,10.9,...,11.5,11.5,11.5,11.5,11.5,11.5,435.059,353.028,107.7,-11.980

In [13]:
df.loc[df["SRING_Assy_DATA"] > 0.99]

,H,라인,투입시간,생산일자(완성),파트시리얼,SRING_Assy_DATA,SEAL_PRESS_LOAD,SEAL_PRESS_DISTANCE,NR_DATA#1,NR_DATA#2,...,IVM_Cover_체결_토크_1,IVM_Cover_체결_토크_2,IVM_Cover_체결_토크_3,IVM_Cover_체결_토크_4,IVM_Cover_체결_토크_5,IVM_Cover_체결_토크_6,Bottom_다윌핀_압입력_1,Bottom_다윌핀_압입력_2,캠스프라켓_체결_토크,완성_리크테스트값
1610,신U 조립,U,2019-06-05 오후 2:04:13,2019-06-05 오후 3:50:29,19052218320373A,1.007,29.297,141.399,10.8,10.8,...,11.5,11.5,11.5,11.6,11.5,11.5,389.649,364.747,107.3,-2.113
3147,신U 조립,U,2019-06-11 오전 9:16:45,2019-06-11 오전 10:37:21,19052415580336A,1.001,38.086,141.399,10.7,10.8,...,11.5,11.5,11.5,11.5,11.6,11.5,417.481,347.168,107.1,-10.706
3487,신U 조립,U,2019-06-11 오후 4:42:24,2019-06-12 오전 11:48:45,19052722390084A,1.062,35.157,141.399,10.8,10.9,...,11.5,11.5,11.5,11.5,11.5,11.5,459.961,389.649,107.5,-3.352
4682,신U 조립,U,2019-06-17 오전 9:23:04,2019-06-17 오전 10:54:20,19052904140336A,1.012,27.833,141.399,10.8,10.9,...,11.5,11.5,11.5,11.6,11.6,11.5,492.188,418.946,107.4,-4.604
5489,신U 조립,U,2019-06-18 오후 6:08:01,2019-06-19 오전 9:38:04,19060201300205A,2.513,46.875,141.399,10.9,10.9,...,11.5,11.5,11.5,11.6,11.5,11.5,410.157,344.239,107.2,-2.871
6936,신U 조립,U,2019-06-25 오전 10:40:26,2019-06-25 오후 1:37:16,19061412550143A,0.994,27.833,141.399,10.7,10.7,...,11.5,11.6,11.5,11.5,11.5,11.5,392.579,325.196,107.6,-2.556

In [17]:
x =[]
for i in list(range(len(df.columns))):
    name = df.columns[i]
    counts = df[df.columns[i]].unique().shape[0]
    dtype = df.dtypes[i]
    x.append((name.counts.dtype))

AttributeError: 'str' object has no attribute 'counts'